server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personalize
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1:8b
        options:
          temperature: 0.2
      embedding:
        model: nomic-embed-text

app:
  assets:
    root: assets
    version: "2025-10-01"
    attributes:
      csv: "classpath:attribute_mapping.csv"   # path to your CSV (can be file: or classpath:)
      enabled: true

